# Generated by Django 3.2.6 on 2021-10-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_profile', '0004_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
