# Generated by Django 3.2.6 on 2021-11-22 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_datatables', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
